name: fem-complete-go

services:
  dev:
    container_name: "fem-complete-go-dev"
    image: "${IMAGE:-dimwittedmonkey}/dev-gopsql:latest"
    volumes:
      - "${SOURCE:-~/src}:/workspace"
      - "${SSH:-~/.ssh}:/homeneodev/.ssh"
    ports:
      - "${PORT:-8081}:8081"
    restart: unless-stopped
  db:
    container_name: "fem-complete-go-db"
    image: postgres:12.4-alpine
    volumes:
      - "./database/postgres-data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    restart: unless-stopped
  test_db:
    container_name: "fem-complete-go-test-db"
    image: postgres:12.4-alpine
    volumes:
      - "./database/postgres-data:/var/lib/postgresql/data:rw"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    restart: unless-stopped
