name: fem-complete-go

services:
  dev:
    container_name: "fem-complete-go-dev"
    image: dimwittedmonkey/dev-env:latest
    volumes:
      - "${SOURCE:-~/src}:/workspace"
    ports:
      - "8081:8081"
    environment:
      UID: "${UID}"
      GID: "${GID}"
    restart: unless-stopped
  db:
    container_name: "fem-complete-go-db"
    image: postgres:12.4-alpine
    volumes:
      - "./database/postgres-data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    restart: unless-stopped
